services:
  ide:
    container_name: ${COMPOSE_PROJECT_NAME:-deovim}_ide_container
    entrypoint: ${USER_HOME_DIR:-/root}/.bin/ide.entrypoint.sh
    environment:
      - COMPOSE_PROJECT_NAME
      - USER_HOME_DIR
    image: ${COMPOSE_PROJECT_NAME:-deovim}_ide_image
    init: true
    ulimits:
      core:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: tmpfs
        target: /tmp
      - type: volume
        source: user_config
        target: ${USER_HOME_DIR:-/root}/.config
        volume:
          nocopy: false
      - type: volume
        source: user_local
        target: ${USER_HOME_DIR:-/root}/.local
        volume:
          nocopy: false
volumes:
  user_config:
  user_local:
